### ISSUE TITLE
darwin -> linux/amd64 & linux -> darwin/amd64 builds do not work

### ISSUE THREAD

**Issue by jchenry** [mitchellh/gox#28]
when a linux build is compiled on darwin and vise versa, the builds complete but when attempting to execute the compiled binaries on their target os' the binaries will simply exit, no failure, just simply exit. 

compiles are against go 1.3.1

**Comment by rubenv** [comment]
Just started seeing this too, executable exits with `Illegal instruction: 4` (built on Linux, run on Darwin).

**Comment by mitchellh** [comment]
Hm, we're not seeing this issue. Do you have any more info? This might be cgo or some other related thing. All our projects and all our devs use Gox to cross compile and we run our apps on Linux as well. Closing as invalid until there is more info... since clearly something is here, but not wide spread enough.
