### ISSUE TITLE
undefined: syscall.EPIPE error goxing with osarch plan9/386 on OS X 10.10.1

### ISSUE THREAD

**Issue by cliffano** [mitchellh/gox#38]
I'm getting 'undefined: syscall.EPIPE' error when compiling with osarch plan9/386.
All the other osarches work fine. Any idea what could be causing this error?

```
> go version
go version go1.4.1 darwin/amd64

> gox -osarch="plan9/386"
Number of parallel builds: 4

-->       plan9/386: _/Users/cliffano/dev/workspace/packer-post-processor-json-updater

1 errors occurred:
--> plan9/386 error: exit status 2
Stderr: # github.com/mitchellh/packer/packer
../../go/src/github.com/mitchellh/packer/packer/ui.go:292: undefined: syscall.EPIPE
```

**Comment by ereyes01** [comment]
I'm getting the same in one of my builds. I think the cause is that what you're building (packer) uses the platform-dependent `syscall` package, and the plan9 implementation of that package simply does not implement syscall.EPIPE, or have it defined anywhere.

I got around this by running `gox -os='!plan9'` to suppress builds for plan9.

I suppose you could also try changing packer to not rely on syscall, which by definition is not cross-platform, to "os" or some other platform-independent package instead, depending on what that code is doing.

**Comment by mitchellh** [comment]
@ereyes01 is correct, this isn't Gox so much as your code can't be compiled on plan9.
